# Use the latest Node.js image as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set the environment variable for Node.js options
ENV NODE_OPTIONS=--openssl-legacy-provider

# Define the build argument for the environment variable
ARG REACT_APP_BACKEND_URL
# Set the environment variable for the build
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

# Build the application for production
RUN npm run build

# Install serve to run the built application
RUN npm install -g serve

# Expose the port the app runs on
EXPOSE 3999

# Start the application using serve on port 3999
CMD ["serve", "-s", "build", "-l", "3999"]
